### ISSUE TITLE
Some props are not implemented

### ISSUE THREAD

**Issue by dovfrank** [sghiassy/react-native-sglistview#14]
I tried your component, it does not work because I'm using the following which are not defined:
scrollProperties
getScrollResponder()

**Comment by hmm29** [comment]
+1
I love react-native-sglistview but yea, @dovfrank is right; the fact that scrollProperties aren't implemented is quite an issue. Could you please implement this, @sghiassy?

**Comment by SeanXiao1988** [comment]
+1

**Comment by sghiassy** [comment]
Thanks for the feedback. I'll try to get to this in the next couple days.

**Comment by hmm29** [comment]
Sweet. Thanks, @sghiassy ; can't wait to be able to add it back to my project soon

**Comment by sghiassy** [comment]
Glad to say this is now fixed.

For future reference, you can always access the underlying `ListView` from `SGListView` by using the `getNativeListView` function.

So while now you can do:

``` js
this.refs.sglistview.getScrollResponder();
```

in previous version you can do:

``` js
this.refs.sglistview.getNativeListView().getScrollResponder();
```

**Comment by hmm29** [comment]
You are awesome. Thanks so much

My best,
Harrison Miller
Yale College '16
