### ISSUE TITLE
Enhancement: Pull to refresh.

### ISSUE THREAD

**Issue by varqasim** [sghiassy/react-native-sglistview#16]
Currently If I want a pull to refresh I would need to use another react-native library, but since SGListView is the best out there I think if it has a pull to refresh it would be the perfect go to ListView component.

**Comment by sghiassy** [comment]
Good idea. I'm pretty slammed at work for the next two weeks. But I'll try to implement that shortly thereafter.

**Comment by varqasim** [comment]
@sghiassy any updates :+1:

**Comment by sghiassy** [comment]
Unfortunately no. Way busy with work, so I don't see myself being able to implement this in the short - medium term. Sorry

**Comment by lananelson** [comment]
I am able to just pass refresh control as a prop and it works great

```
          <SGListView
                dataSource={dataSource}
                onEndReached={this.onEndReached}
                refreshControl={
                      <RefreshControl
                        refreshing={this.isRefreshing()}
                        onRefresh={() => { this.onRefresh(); }}
                        tintColor={"white"}
                        colors={[ "white" ]}
                        progressBackgroundColor="#fff"
                      />}
                showsVerticalScrollIndicator={false}
                renderRow={this.createRow}
                style={S.flex1} />
```

**Comment by rreusser** [comment]
Haven't tested it explicitly with this component, but yeah, swapping in the built-in refresh control was shockingly easy anywhere I happened to need it.
