### ISSUE TITLE
Fast scroll top top (via tapping status bar) leads to empty page

### ISSUE THREAD

**Issue by udfalkso** [sghiassy/react-native-sglistview#2]
When I have scrolled down quite a bit in my long list view and then tap the status bar to cause it to quickly scroll up, the list is blank.  Moving it slightly with my finger causes it to re-draw correctly.  

It's not every time, but often.

**Comment by sghiassy** [comment]
Hmm... I tried to reproduce the issue but couldn't. I'll try again, but if there's anything you can send me to help repo the problem, that'd be helpful.

**Comment by udfalkso** [comment]
I can't seem to reproduce it anymore either.  It did happen before... I swear
