### ISSUE TITLE
The Readme is to sample difficult to use

### ISSUE THREAD

**Issue by cbcye** [sghiassy/react-native-sglistview#29]
I try to following the steps of Readme to change ListView to SGListView, just change the tag valud and datasource but there has make many error.  then to read the example it is difficult to modify for my code. if can hope can make a friendly Readme document

**Comment by sghiassy** [comment]
Sorry to hear it was confusing. I'm pretty slammed unfortunately - but feel free to submit a PR to update the README. Thx

**Comment by sghiassy** [comment]
Updated
