### ISSUE TITLE
Required prop `renderScrollComponent` was not specified in `SGListView`.

### ISSUE THREAD

**Issue by udfalkso** [sghiassy/react-native-sglistview#3]
2015-08-09 21:34:02.691 [warn][tid:com.facebook.React.JavaScript] 'Warning: Failed propType: Required prop `renderScrollComponent` was not specified in `SGListView`. Check the render method of `Feed`.'

Is there something I need to do to get rid of this warning?  Thanks!

**Comment by sghiassy** [comment]
Looks like `renderScrollComponent` is a new prop added by the React team in `0.8.0`. 

I updated `SGListView.js` in master to fix the problem. Can you copy and paste the file into your project and let me know the results?

If everything looks good, I'll publish the changes to NPM.

**Comment by udfalkso** [comment]
Yup, the warning has gone away.  Thanks

**Comment by sghiassy** [comment]
Nice. Thx for the confirm. I posted the update to NPM
