### ISSUE TITLE
Question: Is SGListView better for fixed height or variable height implementations?

### ISSUE THREAD

**Issue by mschipperheyn** [sghiassy/react-native-sglistview#36]
Perhaps this is something that the documentation can address since a lot of the discussion around listviews focused on the question of whether it optimizes for fixed height or variable height components.

**Comment by sghiassy** [comment]
It shouldn't really make a difference. The optimization strategy would apply equally as well to both fixed height and variable height cells.

**Comment by sibelius** [comment]
@mschipperheyn this is better for fixed height list view https://github.com/brentvatne/fixed-height-windowed-list-view-experiment
