### ISSUE TITLE
Cells remain visible in premptiveLoading

### ISSUE THREAD

**Issue by paramaggarwal** [sghiassy/react-native-sglistview#4]
Hi @sghiassy thank you for this wonderful component. I have been using a similar implementation, but never got around to pulling it out into a library and open sourcing it. Also, I like your method to use `ref`s to the individual cells. In my case, I was trying to handle everything at the `ListView` layer itself.

I had been trying to implement something like `premptiveLoading` in my implementation and was hitting an issue where some cell would be pre-emptively made visible, but if you started scrolling in the other direction they would simply remain visible. This unfortunately is happening in your implementation too.

Here is a screenshot of my view hierarchy. I scrolled down and then scrolled up. You can see the current viewport in the screenshot below. The two stray cards at the bottom are the ones that were pre-emptively rendered but never hidden again.

<img width="61" alt="screen shot 2015-08-14 at 6 52 09 am" src="https://cloud.githubusercontent.com/assets/543981/9265511/9f61124a-4251-11e5-9001-9f8d169a1026.png">

Here is the snippet of code that causes this:

```
// Preemptivly set cells
    for (var i = 1; i <= props.premptiveLoading; i++) {
      var cell;

      if (isScrollingUp){
        cell = cellData[section][lastRow - i];
      } else if (isScrollingDown) {
        cell = cellData[section][lastRow + i];
      }

      if (cell) {
        cell.setVisibility(true);
      } else {
        break;
      }
    }
```

Here you will notice that a cell on which we call `setVisibility(true)` is never set back to not be visible if we start scrolling in the opposite direction! I have forked your library into my project and will continue making some modifications for this and other things and will come back with a PR. Thanks again!

**Comment by sghiassy** [comment]
nice! thanks for the PR. I'll check it out

**Comment by sghiassy** [comment]
btw - are you getting the view screenshot from Xcode UI Inspector? Or Reveal? I've been hoping to use Reveal with my RN project but haven't gotten it to work yet.

**Comment by paramaggarwal** [comment]
@sghiassy I used Xcode's View Inspector.

**Comment by sghiassy** [comment]
Little slow on getting to this. Should be able to review the PR sometime this weekend. Cheers
