### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by L-Jovi** [sghiassy/react-native-sglistview#52]
thanks for your smart project first :)

my node version `v6.3.1`
my npm version `v3.10.3`

I install failed,

`npm install react-native-sglistview --save`

output

`npm ERR! cb() never called!`

what should I do?

thanks for your time.

**Comment by sghiassy** [comment]
Looks like there was a problem when I published the package originally using `yarn`. I bumped the version to `0.3.5` and published with `npm` now. Should work. Cheers

**Comment by L-Jovi** [comment]
@sghiassy  hi, thanks for your reply, I try install again and it works, but when I run my project, some __naming collision__ error throw like below image,

![image](https://cloud.githubusercontent.com/assets/7262199/23346994/dff6a2e0-fcd9-11e6-91f6-a2c1fc57fa3d.png)

would you mind have a look?

thanks again, regards.
