### ISSUE TITLE
Duplicate module name: ReactNative

### ISSUE THREAD

**Issue by markgoodyear** [sghiassy/react-native-sglistview#53]
When install the package, packager throws up this error:

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ReactNative
  Paths: /{project path here}/node_modules/react-native-sglistview/node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNative.js 
  collides with /{project path here}/node_modules/react-native/Libraries/react-native/ReactNative.js
```

I'm using RN 0.36. Any ideas on how to fix the issue? Cheers!

**Comment by younisshah** [comment]
@markgoodyear Update your react-native version to `0.41.2`

**Comment by markgoodyear** [comment]
@younisshah Unfortunately I'm not able to update at the moment (due to the project). Is there anyway you could add support for lower versions? If not, I think it'd be a great idea to add in the versions supported in the readme.

**Comment by sghiassy** [comment]
I've wondered how RN modules version themselves to target different RN versions. Are there any good examples of this?

**Comment by yjb94** [comment]
@markgoodyear  will this help?
`rm -r node_modules/react-native-sglistview/node_modules`

**Comment by laukaichung** [comment]
@yjb94 
It works! Does it have anything to do with the RN 0.42 update?

**Comment by markgoodyear** [comment]
@yjb94 — I've not tried that. I've managed to have some time out to update the RN version in the project I'm working on (not tested `sglistview` yet as it's still in progress, big jump so lots of breaking changes to fix first), but good to hear it works from @stonecold123!

**Comment by markgoodyear** [comment]
@yjb94, after updating to the latest RN version (0.42) I get:

```
Duplicate module name: react-native-vector-icons
````

Removing the `node_modules` manually works though.

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by sghiassy** [comment]
I updated the dependency structure to avoid installing `react-native` under its own `node_modules` folder. I tested the changes in an example app and they worked for me - so I believe this problem is fixed.

Please reopen and provide repo steps if the newest version doesn't solve the problem.
