### ISSUE TITLE
undefined is not an object (evaluating '_react.proptypes.element')

### ISSUE THREAD

**Issue by alicompiler** [sghiassy/react-native-sglistview#62]
`
import SGListView from 'react-native-sglistview';
`
i'm just importing the listview and i got

> undefined is not an object (evaluating '_react.proptypes.element')

react-native-cli: 2.0.1
react-native: 0.49.3

**Comment by libdib** [comment]
PropTypes have been moved to a separate package as of 0.48 (as I recall).

**Comment by TolgaCagin** [comment]
Same Problem
react-native-cli: 2.0.1
react-native: 0.50.4

**Comment by martinbynder** [comment]
@TolgaCagin Import react native prop-types and create-react-class. You have to modify this package in general. Link below was quite helpful for me to do so:
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass

**Comment by martinosmartinos** [comment]
@TolgaCagin Import react native prop-types and create-react-class. You have to modify this package in general. Link below was quite helpful for me to do so:
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass

**Comment by danielgarciasantos** [comment]
Same Problem

**Comment by martinosmartinos** [comment]
@danielgarciasantos you have to modify this package and include where applicable (SGListView.js, SGViewCell.js) :
var PropTypes = require('prop-types');
var createReactClass = require('create-react-class');

Follow https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass and your 'red screen of death' for further modifications.

**Comment by sghiassy** [comment]
Can you submit a PR? That’d be great

**Comment by martinosmartinos** [comment]
Sure, will do!

**Comment by danielgarciasantos** [comment]
I wait for RD,

**Comment by martinosmartinos** [comment]
Done. Should be in a review now.

**Comment by danielgarciasantos** [comment]
merged 👍 ?

**Comment by martinosmartinos** [comment]
@danielgarciasantos it is not up to me anymore:) You could try get changes from latest PR and see if it works for you.

**Comment by danielgarciasantos** [comment]
Okay, thanks, I'll try.

**Comment by danielgarciasantos** [comment]
resolved with PR..... @martinosmartinos

**Comment by martinosmartinos** [comment]
@danielgarciasantos good to hear!
